// src/components/CreatePost.js
import React, { useState } from 'react';
import { createPost, generateAIContent } from '../api';
import { toast } from 'react-toastify'; // Import react-toastify

const CreatePost = ({ onPostCreated }) => {
    const [title, setTitle] = useState('');
    const [content, setContent] = useState('');
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState('');

    // Function to generate content with AI
    const handleGenerateAIContent = async () => {
        setLoading(true);
        setError('');
        try {
            console.log('AI content generation button clicked.');
            const aiData = await generateAIContent();
            console.log('Data generated by AI:', aiData);
            setTitle(aiData.title);
            setContent(aiData.content);
            toast.success('Content has been successfully created with AI.');
        } catch (err) {
            console.error('Error generating AI content:', err);
            setError('An error occurred while generating content with AI.');
            toast.error('An error occurred while generating content with AI.');
        }
        setLoading(false);
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        if (!title || !content) {
            alert('Title and content cannot be empty');
            return;
        }

        try {
            console.log('Starting post creation process.');
            const newPost = await createPost({ title, content });
            console.log('New post created:', newPost);
            onPostCreated(newPost);
            setTitle('');
            setContent('');
        } catch (error) {
            console.error('Error occurred while creating the post:', error);
            alert('An error occurred while creating the post.');
            toast.error('An error occurred while creating the post.');
        }
    };

    return (
        <div className="neumorphic-card">
            <h2>Create New Post</h2>
            <button
                onClick={handleGenerateAIContent}
                disabled={loading}
                className="neumorphic-button"
                style={{ width: '100%', marginBottom: '20px' }}
            >
                {loading ? 'Generating... Please wait, estimated wait time: 10 seconds' : 'Generate Content with AI'}
            </button>
            {error && <p style={{ color: 'red' }}>{error}</p>}
            <form onSubmit={handleSubmit}>
                <div>
                    <label>Title:</label><br />
                    <input
                        type="text"
                        value={title}
                        onChange={(e) => setTitle(e.target.value)}
                        className="neumorphic-input"
                        placeholder="Enter title"
                    />
                </div>
                <div>
                    <label>Content:</label><br />
                    <textarea
                        value={content}
                        onChange={(e) => setContent(e.target.value)}
                        rows="10"
                        className="neumorphic-textarea"
                        placeholder="Enter content"
                    ></textarea>
                </div>
                <button type="submit" className="neumorphic-button" style={{ width: '100%' }}>
                    Publish Post
                </button>
            </form>
        </div>
    );
};

export default CreatePost;
